# Generated by Django 5.2.6 on 2025-10-01 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Content Page', 'verbose_name_plural': 'Content Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='The main HTML content of the page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text="URL-friendly identifier (e.g., 'about-us').", unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The main title of the page.', max_length=200),
        ),
    ]
