# Generated by Django 5.2.6 on 2025-10-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_banner_menulink_alter_page_options_page_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='order',
            new_name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
